export const StaticData = {
Meta_title:" Connected Kerb - EV Stations",
Meta_description:"Connected Kerb provide a unique approach to electric vehicle charging infrastructure – one that champions sustainability and connectivity.",
locator_breadcrumb:"Station Locator",
facilities:"Facilities:",
Telephone:"Telephone",
openingHours:"Opening Hours",
FindLocationtext:"Find Charging Station",
Usemylocation:"Use my location",
chargerId:"Charger ID",
Status:"Status",
bannerCta:"CONTACT OUR EXPERTS",
Availability:"Chargers Available",
Unavailable:"No Chargers available",
Search:"Search",
Brandname:"Connected Kerb",
miles:"miles",
tempClosed:"Temporarily Closed",
StoreDetailbtn:"View Station Detail",
noStationFound:"No Stations found according to search.",
Storehighlight:"Store Highlights",
Days:"Days",
Hours:"Hours",
Minutes:"Minutes",
Seconds:"Seconds",
getDirection:"Directions",
AllCity:"All Cities of",
NearStoretext:"NEARBY LOCATIONS",
AllLocationtext:"View All Location",
PagenotFound:"404 - Page Not Found",
goHomeCTA:"GO HOME",
StoreFinder:"Store Finder",
FAQs:"FAQs",
DownloadApp:"Download Our App",
cookie:"Privacy & Cookies Policy I Connected Kerb",
About:"Connected Kerb  was officially formed in 2017.",
aboutKerb:"ABOUT CONNECTED KERB",
Closed:"Closed",
DayofWeek:"Day of the Week",
Reopenmessage:"Message - The Station is temporarily closed. It will reopen at",
Address:"Address",
Holdiay:"Our Holdiday Hours",
BacktoTop:"Back to Top",
bannerHeading:"EV charging solutions for a connected future",
bannerPara:"At Connected Kerb,we accelerate the transition to sustainable mobility for all people with reliable, affordable and accessible electric vehicle charging solutions.",
}